[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vibe_vault = "AsRo4gj9W5MW39xRmsToGkjMKesfwujQg97H7KuyVCcM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://detailed-sharleen-fast-devnet.helius-rpc.com"
# cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
